config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :locations do
    member do
      put 'like', to: "locations#upvote" 
      put 'dislike', to: "locations#downvote" 
    end
    resources :comments
    resources :photos
  end
  get '/locations/category/:tag', to: 'locations#category'
  get '/all', to: 'locations#all'
  get '/search', to: 'locations#search'
  get '/my', to: 'locations#my'
  get '/categories', to: 'locations#categories'
  root 'locations#index'
  resources :users, only: [:show]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :location
  belongs_to :user
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :photos, dependent: :destroy
  mount_uploader :image, ImageUploader
  acts_as_votable
  acts_as_taggable
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  belongs_to :location
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :locations, dependent: :destroy
  has_many :comments, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
  has_many :photos, dependent: :destroy
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	# Prevent CSRF attacks by raising an exception.
  	# For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception
    before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) << :name << :avatar 
	  devise_parameter_sanitizer.for(:account_update) << :name << :avatar
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	
	def create
		@location = Location.find(params[:location_id])
		@comment = Comment.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.location_id = @location.id

		if @comment.save 
			redirect_to location_path(@location)
		else
			render 'new'
		end
	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	include ActionView::Helpers::TextHelper
	before_action :find_location, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show, :category, :all, :search, :categories]

	def index
		@locations = Location.all.order("created_at DESC").paginate(:page => params[:page],:per_page => 24)
		 @latest_locations = Location.order("created_at DESC").paginate(:page => params[:page],:per_page => 4)
		 @most_locations = Location.order("created_at DESC").paginate(:page => params[:page],:per_page => 4)
	end

	def categories
		 @locations = Location.order("created_at DESC").paginate(:page => params[:page],:per_page => 24)
	end

	def category
		@locations = Location.all.order("created_at DESC").tagged_with(params[:tag]).paginate(:page => params[:page],:per_page => 24)
		@header=params[:tag].pluralize.capitalize
		render 'all'
	end

	def all
		@locations = Location.all.order("created_at DESC").paginate(:page => params[:page],:per_page => 24)
		@header="All Locations"
	end

	def search
		@locations = Location.all.order("created_at DESC").where("title LIKE ? ", "%#{params[:q]}%").paginate(:page => params[:page],:per_page => 24)
		@header="Search results"
		render 'all'
	end	

	def my
		@locations = Location.all.order("created_at DESC").where(user_id: current_user.id).order("created_at DESC").paginate(:page => params[:page],:per_page => 24)
		# if @locations.empty?
		# 	flash[:notice] = "You have no locations created yet!"
		# end
		render 'all'
	end

	def show
		#@location = Location.find(params[:id])
	# 	@photos = Photo.where(location_id: @location).order("created_at desc").to_a
		@comments = Comment.where(location_id: @location) 
		@tags = Location.find(params[:id]).tag_list
		@photos = Photo.where(location_id: @location)
	end

	def new
		@location = current_user.locations.build
		# @photo = Photo.new(:title => "My photo \##{1 + (Photo.maximum(:id) || 0)}")
	end
	
	def create
		@location = current_user.locations.build(location_params)
		#@location.tag_list.add()
		#@paraams = params[:photo]
		#@photo = Photo.new(params[:photo])
		#@photo.location_id = @location.id
		#@photo.user_id = current_user.id
		#@photo.save


		if @location.save
			redirect_to @location
		else
			render 'new'
		end
	end

	def edit
		@tag_list = @location.tag_list.join(", ")
	end

	def update
		if @location.update(location_params)
			redirect_to @location
		else
			render 'edit'
		end
	end

	def destroy
		@location.destroy
		redirect_to root_path
	end

	def upvote
		@location.upvote_by current_user
	end

	def downvote
		@location.downvote_by current_user
	end

	private

	def find_location
		@location = Location.find(params[:id])
	end

	def location_params
		params.require(:location).permit( :title, :description, :image, :lon, :lat, :tag_list, :page)
	end	
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def create
		@location = Location.find(params[:location_id])
		@photo = Photo.create(params[:photo].permit(:title, :photo))
		@photo.user_id = current_user.id
		@photo.location_id = @location.id

		if @photo.save 
			redirect_to location_path(@location)
		else
			
			redirect_to location_path(@location)
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/comments/_form.html.erb
<div class="row">
	<% if user_signed_in? %>
		<div class="col-md-12 text-center">   
			<%= simple_form_for [@location, @location.comments.build] do |f| %>
			  	<%= f.input :content, label: "Say something about this location...", input_html: { rows: "5", id: "comment", placeholder: "Add comment..." } %>
			 	<%= f.button :submit, class: "btn btn-success btn-comment" %>
			<% end %>
		</div>
	<% else %>
		<div class="col-md-12 text-center">  
		    <div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button> <p class="notice">You have to Log In to comment!</p> 
		    </div>
		</div>
	<% end %>

</div>

app/views/layouts/_notice.html.erb
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12" >
        	<% if notice %>
        	<div class="alert alert-warning alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button> <p class="notice"><%= notice %></p> </div>
        	<% end %>

        	<% if alert %>
        	<div class="alert alert-danger alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button> <p class="notice"><%= alert %></p> </div>
        	<% end %>
        </div>
    </div>

app/views/layouts/_user_controls.html.erb
<% if user_signed_in? %>
	<li>
		<%= link_to "Add New Location", new_location_path, class: "button" %>
	</li>
	<!-- <li> -->
		<ul class="dropdown">
			<a class="dropdown-toggle" data-toggle="dropdown" href="#">
				<%= current_user.name %>
			    <span class="caret"></span>
			</a>
			<ul class="dropdown-menu" style="width:100%">
			    <li><%= link_to "Profile", edit_user_registration_path %></li>
				<li><%= link_to "My Locations", "/my", class: "button" %></li>
				<li><%= link_to "Log out", destroy_user_session_path, :method => :delete  %></li> 
			</ul>
		</ul>       

<% else %>
		<ul class="dropdown">
			<a class="dropdown-toggle" data-toggle="dropdown" href="#">Log In / Sign in
			    <span class="caret"></span>
			</a>
			<ul class="dropdown-menu logins" >
 				<div>
					<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
					    <%= f.input :email, autofocus: true, input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' }  %>
					    <%= f.input :password, required: false, input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group', size: 35} %>

					    <%= f.input :remember_me, wrapper_html: { class: 'chex' }, as: :boolean if devise_mapping.rememberable? %>

					  <div class="form-actions">
					  <%= f.button :submit, "Log in", class: "btn btn-alert"  %>
					  </div>
						<center class="text">OR</center>
					  <div>
					  <%= link_to "Sign up", new_registration_path(resource_name) , class: "btn btn-default" %>
					  </div>
					<% end %>
 				</div>
			</ul>
		</ul>       
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
          <title>Sportloc </title>
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
          <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
          <%= csrf_meta_tags %>
    </head>
    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a href="/" class="navbar-brand">SportLOC</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li >
                    <%= link_to "All Locations", "/all", class: "button" %>
                </li>
                <li><%= link_to "Categories", "/categories", class: "button" %></li>
                <% if user_signed_in? %>
                    <li>
                        <%= link_to "Add New Location", new_location_path, class: "button" %>
                    </li>
                <% end %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <% if user_signed_in? %>
                        <%= current_user.name %>
                    <% else %>
                        Log In 
                    <% end %>
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <% if user_signed_in? %>
                        <li><%= link_to "Profile", edit_user_registration_path %></li>
                        <li><%= link_to "My Locations", "/my", class: "button" %></li>
                        <li role="separator" class="divider"></li>
                        <li><%= link_to "Log out", destroy_user_session_path, :method => :delete  %></li> 
                    <% else %>
                        <li>                            
                            <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), html: { class: 'form logins'}) do |f| %>
                                <%= raw '<div class="form-group">' %>
                                    <%= f.input_field :email, autofocus: true, class: 'form-control', placeholder: 'E-mail'  %>
                                <%= raw '</div>' %>
                                
                                <%= raw '<div class="form-group">' %>
                                    <%= f.input_field :password, required: false, class: 'form-control' , size: 20, placeholder: 'Password' %>
                                <%= raw '</div>' %>

                                <%= raw '<div class="form-group hidden-xs">' %>
                                    <%= f.input_field :remember_me, as: :boolean if devise_mapping.rememberable? %>
                                    Remember me?
                                <%= raw '</div>' %>

                                <%= raw '<div class="btn-group" role="group">' %>

                                    <%= raw '<button type="submit" class="btn btn-default">Log In</button>' %>
                                    <%= link_to "Sign up", new_registration_path(resource_name) , class: "btn btn-default dropdown-signup forced-black", role: "button" %>
                                <%= raw '</div>' %>
                            <% end %>
                        </li> 
                    <% end %>
                  </ul>
                </li>
              </ul>
              <%= render "locations/search" %>
            </div>
          </div>
        </nav>
   <%= yield %>
        <footer class="footer container-fluid text-center">
            <div class="row">
                <br>
                <p>zapalac.peter@gmail.com</p> 
                </div>
        </footer>
    </body>
</html>

app/views/locations/_form.html.erb
<div class="col-md-offset-1 col-md-5 col-sm-12 col-xs-12">
    <%= simple_form_for @location do |f| %>
        <%= f.input :title,required: true, input_html: { class: 'form-control', placeholder: "Give this place a name" }, wrapper_html: { class: 'form-group' }  %>

        <%= f.input :description,required: true,input_html: { class: 'form-control', placeholder: "Say something more about your experience" }, wrapper_html: { class: 'form-group' }  %>
        <%= f.input :image,required: true, :as => :file,input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' }  %>
        <%= f.input :lon,input_html: { class: 'form-control', placeholder: "Just click no the map" }, wrapper_html: { class: 'form-group' }  %>
        <%= f.input :lat ,input_html: { class: 'form-control', placeholder: "Just click no the map" }, wrapper_html: { class: 'form-group' } %>
        <%= f.input :tag_list, :placeholder => "Tags values are separated by commas" ,input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' } %>	
        <%= f.button :submit, class: "btn btn-success form-control" %>
    <% end %>
</div>
<div class="col-md-5 col-sm-12 col-xs-12">
    <div id="map"></div>
</div>

<script type="text/javascript">
	$('#location_tag_list').val("<%= @tag_list %>");
</script>

<%= render "tokens" %>
<%= render "gmaps_set_update" %>

app/views/locations/_gmaps_index.html.erb
<script type="text/javascript">
$('#map_index').height(
    $(window).height() - 50 - $('#footer').height()
);

</script>

<script type="text/javascript">
    
	var map;
	var marker;
	var mLat = 0; 
	var mLon = 0;
	var zoomm = 11;
	var latt = mLat;
		if(mLat === 0){ 
			latt = 48.7205557; 
		}
	var lonn = mLon;
		if(mLon === 0){ 
			lonn = 19.7619074;
		}

	function initMap() {
		map = new google.maps.Map(document.getElementById('map_index'), {
			center: {lat: latt, lng: lonn},
			zoom: zoomm,
			minZoom: 5,
			maxZoom: 20,
			streetViewControl: false
		});

		if (navigator.geolocation) {
         navigator.geolocation.getCurrentPosition(function (position) {
             initialLocation = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
             map.setCenter(initialLocation);
         });
     	}

     	markers = [];
     	<% @locations.each do |location| %>
			marker = new google.maps.Marker({
				position: {lat: <%= location.lat %> , lng: <%= location.lon %>},
				map: map,
				title: '<%= location.title %>'
			}),
			marker.addListener('click', function() {
			    location.href = "/locations/".concat('<%= location.id %>')
			 });
			markers.push(marker);  
		<% end %>
     	
	}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBcqE12ESGUv4dfzOuWrYGJiMuGcRQIZM4&callback=initMap"
        async defer></script>

app/views/locations/_gmaps_set_update.html.erb
<script type="text/javascript">
	var map;
	var marker;
	var mLat = <%= (!@location.lat.nil?) ? @location.lat : 0 %>; 
	var mLon = <%= (!@location.lon.nil?) ? @location.lon : 0 %>;
	var latt = mLat;
		if(mLat === 0){ 
			latt = 48.7205557; 
		}
	var lonn = mLon;
		if(mLon === 0){ 
			lonn = 19.7619074; 
		}

	function initMap() {
		map = new google.maps.Map(document.getElementById('map'), {
			center: {lat: latt, lng: lonn},
			zoom: 7,
			minZoom: 5,
			maxZoom: 20,
			streetViewControl: false
		});

		marker = new google.maps.Marker({
			position: {lat: mLat, lng: mLon},
			map: map
		});

		map.addListener('click', function(event) {
			mLat = event.latLng.lat();
			mLon = event.latLng.lng();
			marker.setPosition(event.latLng);
			$('#location_lat').val(mLat);
			$('#location_lon').val(mLon);
		});
	}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBcqE12ESGUv4dfzOuWrYGJiMuGcRQIZM4&callback=initMap"
        async defer></script>

app/views/locations/_gmaps_show.html.erb
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        var options = { $AutoPlay: true };
        var jssor_slider1 = new $JssorSlider$('slider1_container', options);
    });
    
	var map;
	var marker;
	var mLat = <%= (!@location.lat.nil?) ? @location.lat : 0 %>; 
	var mLon = <%= (!@location.lon.nil?) ? @location.lon : 0 %>;
	var zoomm = 10;
	var latt = mLat;
		if(mLat === 0){ 
			latt = 48.7205557; 
			zoomm = 7;
		}
	var lonn = mLon;
		if(mLon === 0){ 
			lonn = 19.7619074;
			zoomm = 7; 
		}

	function initMap() {
		map = new google.maps.Map(document.getElementById('map_small'), {
			center: {lat: latt, lng: lonn},
			zoom: zoomm,
			minZoom: 5,
			maxZoom: 20,
			streetViewControl: false
		});

		marker = new google.maps.Marker({
			position: {lat: mLat, lng: mLon},
			map: map
		});

	}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBcqE12ESGUv4dfzOuWrYGJiMuGcRQIZM4&callback=initMap"
        async defer></script>

app/views/locations/_search.html.erb
<%= form_tag("/search", method: "get", class: "navbar-form navbar-right search hidden-xs hidden-sm") do %>
  <%= raw '<div class="form-group">' %>
  <%= text_field_tag :q, nil, placeholder: "Search Locations", class: "form-control"  %>
  <%= raw '</div>' %>
  <%= raw '<button type="submit" class="btn btn-default">Search</button>' %>
<% end %>


<!-- <form class="navbar-form navbar-right search" role="search" action="/search" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="✓">
  <div class="form-group">
  <input type="text" name="q" id="q" placeholder="Search Locations" class="form-control">
  </div>
  <button type="submit" class="btn btn-default">Search</button>
</form> -->

app/views/locations/_tokens.html.erb
<script type="text/javascript">
$('#location_tag_list').tokenfield({
	createTokensOnBlur: true,
	limit: 10
});

</script>

	<!-- autocomplete: {
    source: ['family','sport','museum','nice','place','beautiful','mountain','nature','forest','photography','children','village','city','town','food','restaurant','pizza','kebab','flower','castle','history','skiing','ski center','river','lake','art','free time','park','shopping','hobby','holiday'],
    delay: 100
  }, --> 

app/views/locations/all.html.erb
<div class="container content">
  <div class="row">
    <% if @locations.size==0 %>
        <div class="alert alert-warning alert-dismissible fade in" role="alert"> <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button> <p class="notice">There are no Locations yet.</p> </div>
    <% else %>
      <% @locations.each do |location| %>
        <div class="col-md-3 col-sm-6 col-xs-12 small-padding" >
            <div class="location" >
                
              <%= link_to image_tag(location.image.url("thumbnail")), location %>
              <p class="text-right comments-likes">  
                <%= location.comments.count %> <span class="glyphicon glyphicon-comment " aria-hidden="true">
                </span>
                <%= location.get_likes.size %> <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>

              </p>
            <p class="text-center">
              <strong>
                <%= link_to location.title, location %> 
              </strong>
            </p>     
          <h2>
            <% link_to location.title, location %>
          </h2>
          </div>
        </div>
      <% end %>
    <% end %>

    <div class="pagination text-center col-md-12 col-xs-12">
      <%= will_paginate @locations, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

app/views/locations/downvote.js.erb
$('.dislike-btn').bind('ajax:success', function() {
console.log("dislike");
   $('#likes-value').text(<%= @location.get_upvotes.size%> +" Likes");
   $('#dislikes-value').text(<%= @location.get_downvotes.size%>+ " Dislikes");

});

app/views/locations/edit.html.erb
<div class="container content">
  <div class="row">
<%= render "form" %>
  </div>
</div>

app/views/locations/index.html.erb
<div class="container-fluid fill">
    <div class="row" id="map_index_wrapper">
        <div id="map_index"></div>
    </div>
</div> 

<%= render "gmaps_index" %>

app/views/locations/new.html.erb
<div class="container">
    <div class="row">
    	<div class="col-md-12 col-xs-12">
    		<h1>Add new location</h1>
    	   	<p>
            	<div class="alert alert-success alert-dismissible fade in" role="alert"> 
            		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
            			<span aria-hidden="true">×</span>
            		</button> 
            		<p class="notice">
            			Pick title for your brand new location, say something about it, tag it on map, choose picture of it and type in some keywords and voilà, your location is created!
            		</p> 
            	</div>
          	</p>
    	</div>
    	<%= render 'form' %>
    </div>
</div>
<br>

app/views/locations/show.html.erb
<div class="container-fluid">
    <div class="row no-padding">
        <div class=" col-md-6 col-sm-12 col-xs-12">
            <div class="row ">          
                <figure class="col-md-12 col-xs-12 col-xs-12"> 
                    <div id="carousel-example-generic" class="carousel slide gallery" data-ride="carousel"  >
                        <div class="carousel-inner" >
                            <div class="item active">
                                <%= image_tag @location.image.url, class:"img-thumbnail", alt:"gallery image" %>
                            </div> 
                            <% @photos.each do |photo| %>
                            <div class="item" >
                                <%= image_tag photo.photo.url, class:"img-thumbnail", alt:"gallery image" %>
                            </div>  
                            <% end %>                      
                        </div>   
                        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>          
                    </div>  
                </figure>
                <div class="col-md-6 col-xs-6 text-center">     
                    <%= link_to like_location_path(@location), method: :put, remote: true,  :class => "btn btn-default form-control like-btn" do %>
                        <span class="glyphicon glyphicon-thumbs-up glyph-black" ></span>        
                    <% end %>
                </div>
                <div class="col-md-6 col-xs-6 text-center"> 
                    <%= link_to dislike_location_path(@location), method: :put, remote: true, :class => "btn btn-default form-control dislike-btn" do %>
                        <span class="glyphicon glyphicon-thumbs-down glyph-black"></span>
                    <% end %>
                </div>
              
                <div class="col-md-12 col-xs-12 ">
                    <section id="comments">
                        <h2 class="comment_count">
                            <%= pluralize(@location.comments.count, "Comment") %>
                        </h2>
                        <% @comments.each do |comment| %>
                            <div class="comment">
                                <p class="username">
                                    <%= link_to comment.user.name, comment.user %> comented on <%= comment.created_at.strftime('%d %B %Y') %>:
                                </p>
                                <p class="comment-content">
                                    "<%= comment.content %>"
                                </p>
                            </div>
                        <% end %>
                        <%= render "comments/form" %>
                    </section>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-xs-12">
            <div class="row">
                <aside class="col-md-12 col-xs-12 col-sm-12">
                    <div id="map_small">
                    </div>
                </aside>
                <br>
                <aside class="col-md-12 col-xs-12 col-sm-12">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <h2>
                                <%= @location.title%>
                            <h2>
                        </li>
                        <li class="list-group-item">
                            <%= @location.description%>
                        </li>
                        <li class="list-group-item">
                            <span class="glyphicon glyphicon-user glyph-aside"></span> 
                            <%= @location.user.name%>
                        </li>
                        <li class="list-group-item">
                            <%= link_to like_location_path(@location), method: :put, remote: true, :class => "btn" do %>
                                <span class="glyphicon glyphicon-thumbs-up glyph-aside-like"></span>
                            <% end %>
                            <span id="likes-value">
                            <%= @location.get_upvotes.size %> Likes
                            </span>
                        </li>
                        <li class="list-group-item">
                            <%= link_to dislike_location_path(@location), method: :put,remote: true, :class => "btn" do %>
                                <span class="glyphicon glyphicon-thumbs-down glyph-aside-like"></span>
                            <% end %>
                            <span id="dislikes-value">
                            <%= @location.get_downvotes.size %> Dislikes 
                            </span>
                        </li>
                        <li class="list-group-item">
                            <span class="glyphicon glyphicon-map-marker glyph-aside"></span>
                            Lon <%= @location.lon %>, Lat <%= @location.lat %>
                        </li>
                        <li class="list-group-item" style="padding-left:13px">
                            <span class="glyphicon glyphicon glyphicon-tags glyph-aside"></span>
                            <% @location.tag_list.each do |tag| %>
                                <span class="badge tag">
                                    <%= link_to tag, "category/"+tag %>
                                </span>
                            <% end %>
                        </li>
                        <% if user_signed_in? %>
                        <li class="list-group-item">
                            <%= simple_form_for [@location, @location.photos.build] do |f| %>
                                <%= f.input :photo, label: "Add Photo to this location", required: true, input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' } %>
                                <%= f.button :submit,"Add Photo", class: "btn" %>
                            <% end %>
                        </li>
                        <% if current_user.name==@location.user.name %>
                            <li class="list-group-item">
                                <%= link_to "Edit Location", edit_location_path(@location) , class: "btn btn-success edit_btn form-control", style:"margin-bottom: 10px;"%>
                                <%= link_to "Delete Location!", location_path(@location), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger edit_btn form-control" %>
                            </li>
                        <% end %>
                    <% end %>

                    </ul>
                </aside>
            </div>
        </div>
    </div>
</div>
<%= render "gmaps_show" %>

app/views/locations/upvote.js.erb
$('.like-btn').bind('ajax:success', function() {
    console.log("like");
   $('#likes-value').text(<%= @location.get_upvotes.size%> +" Likes");
   $('#dislikes-value').text(<%= @location.get_downvotes.size%>+ " Dislikes");

});

app/views/photos/_form.html.erb
<%= simple_form_for [@location, @location.photos.build] do |f| %>
  <%= f.input :title, label: "TITLE" %>
  <%= f.input :photo, label: "Uploa photo" %>
  <%= f.button :submit, class: "button" %>
<% end %>